
// configuration file for

//   ╔═════╦═════╗   ╔───╦═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗   ╔───────╗   ╔════╗    ╔── MICRORUN
//   ║     ║     ║   ║   ║       ║   ║       ║   ║       ║   ║       ║   ║       ║   ║    ║    ║
//   ║     ║     ║   ║   ║       │   ║       ║   ║       ║   ║       ║   ║       ║   ║    ║    ║
//   ║     ║     ║   ║   ║       │   ╠═══╦═══╝   ║       ║   ╠═══╦═══╝   ║       ║   ║    ║    ║
//   ║     ║     ║   ║   ║       │   ║   ║       ║       ║   ║   ║       ║       ║   ║    ║    ║
//   ║     ║     ║   ║   ║       ║   ║   ║       ║       ║   ║   ║       ║       ║   ║    ║    ║
// ──╩─────╩─────╩───╝   ╚═══════╩───╝   ╚════───╩═══════╩───╝   ╚════───╩═══════╩───╝    ╚════╝

do execute "feh --no-fehbg --bg-fill $HOME/Pictures/wallpapers/desktop/wallpaper.png";
do execute "xrdb $HOME/.Xresources";
do execute "killall jackd pipewire pipewire-pulse sndiod &> /dev/null";
do execute "pulseaudio --start";
do execute "setxkbmap -layout 'us,gr,cz' -variant ',,rus' -option 'grp:alt_shift_toggle'";
do execute "if [ ! \"$(pidof microgesture   )\" ]; then sudo microgesture    -c $HOME/.config/microgesture/microgesture.conf      & fi";
do execute "if [ ! \"$(pidof microcompositor)\" ]; then      microcompositor -c $HOME/.config/microcompositor/microcompositor.conf& fi";
do execute "if [ ! \"$(pidof microbar       )\" ]; then      microbar        -c $HOME/.config/microbar/microbar.conf              & fi";
do execute "if [ ! \"$(pidof microtabber    )\" ]; then      microtabber     -c $HOME/.config/microtabber/microtabber.conf        & fi";
do execute "if [ ! \"$(pidof microsound     )\" ]; then      microsound      -c $HOME/.config/microsound/microsound.conf          & fi";
do execute "if [ ! \"$(pidof microbrightness)\" ]; then      microbrightness -c $HOME/.config/microbrightness/microbrightness.conf& fi";

// b-keycode none | shift | caps | control | mod-1 | mod-2 | mod-3 | mod-4 | mod-5 | any xyz press | release command parameter1 parameter2 parameter3 parameter4 parameter5
grab-keycode                                                         mod-4                39 press           execute "if [ ! \"$(pidof microlauncher)\" ]; then microlauncher -c $HOME/.config/microlauncher/microlauncher.conf& fi";
grab-keycode                                                         mod-4                54 press           execute "if [ ! \"$(pidof microconfiner)\" ]; then microconfiner; else kill $(pgrep microconfiner); fi";
grab-keycode none                                                                        107 press           execute "gnome-screenshot -i&";
grab-keycode                                                         mod-4               107 press           execute "gnome-screenshot";
grab-keycode        shift |                                          mod-4                27 press           restart;

